### ISSUE TITLE
Concurrent map iteration and map write panic

### ISSUE THREAD

**Issue by vkorn** [VolantMQ/volantmq#102]
Greetings, I'm running latest git version built with go 1.10.3 on alpine. With frequent clients re-connects the following issue occurs quite often: 
```
fatal error: concurrent map iteration and map write

goroutine 1825837 [running]:
runtime.throw(0x62dd5b, 0x26)
	/usr/local/go/src/runtime/panic.go:616 +0x60 fp=0x1193f3e4 sp=0x1193f3d8 pc=0x1d3c80
runtime.mapiternext(0x1193f470)
	/usr/local/go/src/runtime/hashmap.go:747 +0x570 fp=0x1193f430 sp=0x1193f3e4 pc=0x1afadc
runtime.mapiterinit(0x5b7278, 0x1175a740, 0x1193f470)
	/usr/local/go/src/runtime/hashmap.go:737 +0x1a0 fp=0x1193f444 sp=0x1193f430 pc=0x1af410
github.com/VolantMQ/volantmq/subscriber.(*Type).Offline(0x117b2000, 0x11820501)
	/go/src/github.com/VolantMQ/volantmq/subscriber/subscriber.go:160 +0x48 fp=0x1193f4a0 sp=0x1193f444 pc=0x50ff30
github.com/VolantMQ/volantmq/clients.(*session).SignalOffline(0x11902000)
	/go/src/github.com/VolantMQ/volantmq/clients/session.go:252 +0x34 fp=0x1193f4ac sp=0x1193f4a0 pc=0x534078
github.com/VolantMQ/volantmq/connection.(*impl).onConnectionCloseStage2.func1()
	/go/src/github.com/VolantMQ/volantmq/connection/connection.go:688 +0x2c fp=0x1193f4b8 sp=0x1193f4ac pc=0x52bda0
github.com/VolantMQ/volantmq/types.(*Once).Do(0x1186631c, 0x1193f528, 0x0)
	/go/src/github.com/VolantMQ/volantmq/types/types.go:107 +0x48 fp=0x1193f4cc sp=0x1193f4b8 pc=0x50acd0
github.com/VolantMQ/volantmq/connection.(*impl).onConnectionCloseStage2(0x118662c0, 0x681cb8, 0x85176e)
	/go/src/github.com/VolantMQ/volantmq/connection/connection.go:687 +0x78 fp=0x1193fb18 sp=0x1193f4cc pc=0x524e0c
github.com/VolantMQ/volantmq/connection.(*impl).(github.com/VolantMQ/volantmq/connection.onConnectionCloseStage2)-fm(0x681cb8, 0x85176e)
	/go/src/github.com/VolantMQ/volantmq/connection/connection.go:344 +0x2c fp=0x1193fb28 sp=0x1193fb18 pc=0x52eed8
github.com/VolantMQ/volantmq/connection.(*impl).onConnectionClose.func1()
	/go/src/github.com/VolantMQ/volantmq/connection/connection.go:748 +0x30 fp=0x1193fb34 sp=0x1193fb28 pc=0x52be3c
github.com/VolantMQ/volantmq/types.(*OnceWait).Do(0x11866300, 0x134f9b60, 0x0)
	/go/src/github.com/VolantMQ/volantmq/types/types.go:79 +0x78 fp=0x1193fb50 sp=0x1193fb34 pc=0x50ac30
github.com/VolantMQ/volantmq/connection.(*impl).onConnectionClose(0x118662c0, 0x681cb8, 0x85176e, 0x0)
	/go/src/github.com/VolantMQ/volantmq/connection/connection.go:747 +0x50 fp=0x1193fb70 sp=0x1193fb50 pc=0x525868
github.com/VolantMQ/volantmq/connection.(*impl).(github.com/VolantMQ/volantmq/connection.onConnectionClose)-fm(0x681cb8, 0x85176e, 0x0)
	/go/src/github.com/VolantMQ/volantmq/connection/connection.go:246 +0x2c fp=0x1193fb84 sp=0x1193fb70 pc=0x52edfc
github.com/VolantMQ/volantmq/connection.(*impl).Stop(0x118662c0, 0x681cb8, 0x85176e, 0x50acb8)
	/go/src/github.com/VolantMQ/volantmq/connection/connection.go:358 +0x30 fp=0x1193fb94 sp=0x1193fb84 pc=0x5225a0
github.com/VolantMQ/volantmq/clients.(*session).stop.func1()
	/go/src/github.com/VolantMQ/volantmq/clients/session.go:73 +0x40 fp=0x1193fba8 sp=0x1193fb94 pc=0x53acd4
github.com/VolantMQ/volantmq/types.(*Once).Do(0x11902054, 0x134f9bcc, 0x5a5410)
	/go/src/github.com/VolantMQ/volantmq/types/types.go:107 +0x48 fp=0x1193fbbc sp=0x1193fba8 pc=0x50acd0
github.com/VolantMQ/volantmq/clients.(*session).stop(0x11902000, 0x8e)
	/go/src/github.com/VolantMQ/volantmq/clients/session.go:72 +0x40 fp=0x1193fbd8 sp=0x1193fbbc pc=0x532b68
github.com/VolantMQ/volantmq/clients.(*Manager).loadContainer(0x117a20a0, 0x6836c0, 0x117fe0b0, 0x11800780, 0x119a6060, 0x117fe0b0, 0x118221b0, 0x1192265c)
	/go/src/github.com/VolantMQ/volantmq/clients/sessions.go:560 +0xb34 fp=0x1193fe20 sp=0x1193fbd8 pc=0x5377d8
github.com/VolantMQ/volantmq/clients.(*Manager).newSession(0x117a20a0, 0x6843b8, 0x117fe0b0, 0x11800780, 0x118221b0, 0x119a6060)
	/go/src/github.com/VolantMQ/volantmq/clients/sessions.go:446 +0x1ac fp=0x1193fe80 sp=0x1193fe20 pc=0x536938
github.com/VolantMQ/volantmq/clients.(*Manager).OnConnection(0x117a20a0, 0x686b90, 0x119a6000, 0x119a6060, 0x0, 0x0)
	/go/src/github.com/VolantMQ/volantmq/clients/sessions.go:343 +0x410 fp=0x1193ff84 sp=0x1193fe80 pc=0x536298
github.com/VolantMQ/volantmq/transport.(*baseConfig).handleConnection(0x1184e120, 0x686b90, 0x119a6000)
	/go/src/github.com/VolantMQ/volantmq/transport/base.go:99 +0x8c fp=0x1193ffb0 sp=0x1193ff84 pc=0x51ee9c
github.com/VolantMQ/volantmq/transport.(*tcp).Serve.func1(0x1184e120, 0x686c20, 0x1170e000)
	/go/src/github.com/VolantMQ/volantmq/transport/tcp.go:161 +0xe8 fp=0x1193ffdc sp=0x1193ffb0 pc=0x5206c8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1015 +0x4 fp=0x1193ffdc sp=0x1193ffdc pc=0x201af8
created by github.com/VolantMQ/volantmq/transport.(*tcp).Serve
	/go/src/github.com/VolantMQ/volantmq/transport/tcp.go:155 +0xa0

goroutine 1 [chan receive, 139 minutes]:
main.main()
	/go/src/github.com/VolantMQ/volantmq/main.go:688 +0xc74

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x76d98fc0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x11780514, 0x72, 0x240c00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x8c
internal/poll.(*pollDesc).waitRead(0x11780514, 0xffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Accept(0x11780500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:372 +0x174
net.(*netFD).accept(0x11780500, 0x1a86d0, 0x1a8668, 0x11800880)
	/usr/local/go/src/net/fd_unix.go:238 +0x20
net.(*TCPListener).accept(0x119889d8, 0x11800880, 0x5ae9b0, 0x5ae9b0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x20
net.(*TCPListener).AcceptTCP(0x119889d8, 0x1ff0dc, 0x11729728, 0x1172972c)
	/usr/local/go/src/net/tcpsock.go:246 +0x3c
net/http.tcpKeepAliveListener.Accept(0x119889d8, 0x63da48, 0x11800840, 0x683e20, 0x119a0a80)
	/usr/local/go/src/net/http/server.go:3216 +0x1c
net/http.(*Server).Serve(0x117c0600, 0x683c00, 0x119889d8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2770 +0x150
net/http.(*Server).ListenAndServe(0x117c0600, 0x117297dc, 0x1)
	/usr/local/go/src/net/http/server.go:2711 +0x84
main.main.func2.1(0x11988538)
	/go/src/github.com/VolantMQ/volantmq/main.go:631 +0xd4
created by main.main.func2
	/go/src/github.com/VolantMQ/volantmq/main.go:624 +0x3c

goroutine 34 [syscall, 139 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x130
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 39 [chan receive]:
github.com/VolantMQ/volantmq/topics/mem.(*provider).publisher(0x1184ec60)
	/go/src/github.com/VolantMQ/volantmq/topics/mem/topics.go:251 +0x230
created by github.com/VolantMQ/volantmq/topics/mem.NewMemProvider
	/go/src/github.com/VolantMQ/volantmq/topics/mem/topics.go:95 +0x66c

goroutine 40 [chan receive]:
github.com/VolantMQ/volantmq/topics/mem.(*provider).retainer(0x1184ec60)
	/go/src/github.com/VolantMQ/volantmq/topics/mem/topics.go:242 +0xa0
created by github.com/VolantMQ/volantmq/topics/mem.NewMemProvider
	/go/src/github.com/VolantMQ/volantmq/topics/mem/topics.go:100 +0x6bc

goroutine 43 [IO wait]:
internal/poll.runtime_pollWait(0x76d98f40, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x11780064, 0x72, 0x240c00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x8c
internal/poll.(*pollDesc).waitRead(0x11780064, 0xffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Accept(0x11780050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:372 +0x174
net.(*netFD).accept(0x11780050, 0x1, 0x1, 0x1dd3f4)
	/usr/local/go/src/net/fd_unix.go:238 +0x20
net.(*TCPListener).accept(0x1177e5a8, 0x1173de2c, 0x1ff0dc, 0x1173de28)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x20
net.(*TCPListener).Accept(0x1177e5a8, 0x63d3d0, 0x1184e120, 0x686c20, 0x1170e000)
	/usr/local/go/src/net/tcpsock.go:259 +0x3c
github.com/VolantMQ/volantmq/transport.(*tcp).Serve(0x1184e120, 0x117920a0, 0xd)
	/go/src/github.com/VolantMQ/volantmq/transport/tcp.go:126 +0x3c
github.com/VolantMQ/volantmq/server.(*server).ListenAndServe.func1(0x11890480, 0x684b88, 0x1184e120)
	/go/src/github.com/VolantMQ/volantmq/server/volantmq.go:245 +0x268
created by github.com/VolantMQ/volantmq/server.(*server).ListenAndServe
	/go/src/github.com/VolantMQ/volantmq/server/volantmq.go:222 +0x2f0

goroutine 44 [select, 139 minutes, locked to thread]:
runtime.gopark(0x63dd38, 0x0, 0x61a0e7, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:291 +0xfc
runtime.selectgo(0x1172a7a0, 0x11840240)
	/usr/local/go/src/runtime/select.go:392 +0xea0
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:549 +0x1c0
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1015 +0x4

goroutine 113 [IO wait]:
internal/poll.runtime_pollWait(0x76d98dc0, 0x72, 0x1185c000)
	/usr/local/go/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x117ce1a4, 0x72, 0xffffff00, 0x682408, 0x84cac4)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x8c
internal/poll.(*pollDesc).waitRead(0x117ce1a4, 0x1185c000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Read(0x117ce190, 0x1185c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x148
net.(*netFD).Read(0x117ce190, 0x1185c000, 0x1000, 0x1000, 0x1173fe54, 0x23f10c, 0x117ce190)
	/usr/local/go/src/net/fd_unix.go:202 +0x38
net.(*conn).Read(0x1170e558, 0x1185c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x58
github.com/VolantMQ/volantmq/transport.(*connTCP).Read(0x1170c380, 0x1185c000, 0x1000, 0x1000, 0x79a, 0x879e10, 0x72)
	/go/src/github.com/VolantMQ/volantmq/transport/connTCP.go:20 +0x40
bufio.(*Reader).fill(0x1173ffb8)
	/usr/local/go/src/bufio/bufio.go:100 +0x104
bufio.(*Reader).Peek(0x1173ffb8, 0x2, 0x0, 0x0, 0x0, 0x700, 0x5272e8)
	/usr/local/go/src/bufio/bufio.go:132 +0x28
github.com/VolantMQ/volantmq/connection.(*reader).readPacket(0x1194c3f0, 0x1173ffb8, 0xbed433f1, 0xda21cded, 0x79a, 0x879e10)
	/go/src/github.com/VolantMQ/volantmq/connection/reader.go:124 +0x58
github.com/VolantMQ/volantmq/connection.(*reader).routine(0x1194c3f0)
	/go/src/github.com/VolantMQ/volantmq/connection/reader.go:79 +0xfc
created by github.com/VolantMQ/volantmq/connection.(*reader).run
	/go/src/github.com/VolantMQ/volantmq/connection/reader.go:51 +0x48

goroutine 1825875 [runnable]:
github.com/VolantMQ/volantmq/connection.(*writer).routine(0x133f0380)
	/go/src/github.com/VolantMQ/volantmq/connection/writer.go:340
created by github.com/VolantMQ/volantmq/connection.(*writer).run
	/go/src/github.com/VolantMQ/volantmq/connection/writer.go:282 +0x90

goroutine 1825851 [runnable]:
time.Now(0x687a40, 0x118d21c0, 0x0, 0x0, 0x0)
	/usr/local/go/src/time/time.go:1043 +0xe8
github.com/VolantMQ/volantmq/connection.(*reader).routine(0x11786e70)
	/go/src/github.com/VolantMQ/volantmq/connection/reader.go:74 +0x19c
created by github.com/VolantMQ/volantmq/connection.(*reader).run
	/go/src/github.com/VolantMQ/volantmq/connection/reader.go:51 +0x48
```

Maybe it makes sense to use mutex around foreach?

**Comment by troian** [comment]
Thanks for reporting,
Seems thread doing write is missed from dump?
Can I have example of your test setup to reproduce?

**Comment by vkorn** [comment]
I'm running armv6 docker image, unfortunately it's the only error I can get out of the logs. 
Setup has nothing special: multiple clients are connecting to VolantMQ server but they can reconnect under certain circumstances, I feel like it might have something to do with it. Even though I'm explicitly calling Disconnect it seems that session is still present in VolantMQ. There're A LOT of such entries in logs:

```
2018-08-13T19:06:06Z	INFO	Session duplicate: clientId: gohome allowed: true
``` 

I don't have a consistent steps to reproduce the issue, it happened 12 times during the past 9 days. If it helps, from go part of the code I'm using paho client.

**Comment by troian** [comment]
Seems I caught the cause

**Comment by troian** [comment]
Can you try latest master plz

**Comment by vkorn** [comment]
Thx, I've re-deployed broker, will monitor for a few days to see whether issue is still present. 

Btw, about duplicate session: now it's only during the initial connections. I'm establishing connection to the broker and then invoking subscriptions (around 20 topics). Sometimes, during these subscriptions I'm getting disconnects, which lead to re-subbing attempts cycle. I'll try to put a slight delay between subscriptions to see whether it helps.

**Comment by vkorn** [comment]
I think it's safe to say that this issue has been fixed, no errors for 3 days. Thank you for the fix.
