### ISSUE TITLE
panic: could not get file descriptor / panic: send on closed channel

### ISSUE THREAD

**Issue by MarcMagnin** [VolantMQ/volantmq#86]
Hi,
Thanks for the hard work.
I'd like to use VolantMQ broker and I've followed the examples but when I try to connect to tcp within paho client I have the following error:

```
panic: send on closed channel

goroutine 39 [running]:
github.com/VolantMQ/volantmq/connection.(*impl).connectionRoutine(0xc420126000)
        /home/marc/go/src/github.com/VolantMQ/volantmq/connection/receiver.go:86 +0x156
github.com/VolantMQ/volantmq/connection.(*impl).rxConnection.func2(0xc420126000)
        /home/marc/go/src/github.com/VolantMQ/volantmq/connection/receiver.go:36 +0x2d
created by github.com/VolantMQ/volantmq/connection.(*impl).rxConnection
        /home/marc/go/src/github.com/VolantMQ/volantmq/connection/receiver.go:35 +0x78
```

Connecting to websocket I got:

```
panic: could not get file descriptor

goroutine 37 [running]:
github.com/troian/easygo/netpoll.Must(0x0, 0x80f260, 0xc420010ee0, 0x80f260)
        /home/marc/go/src/github.com/troian/easygo/netpoll/handle.go:46 +0x56
github.com/VolantMQ/volantmq/connection.(*impl).Accept(0xc4202e8000, 0xd, 0xd, 0x7fddbf716200)
        /home/marc/go/src/github.com/VolantMQ/volantmq/connection/connection.go:295 +0xa0
github.com/VolantMQ/volantmq/clients.(*Manager).Handle(0xc4202f20f0, 0x7fddc203c1f0, 0xc4200703c0, 0x7fddbf70e740, 0xc42000c140, 0x7fddbf4f7aa0, 0xc420027701)
        /home/marc/go/src/github.com/VolantMQ/volantmq/clients/sessions.go:233 +0x38c
github.com/VolantMQ/volantmq/transport.(*baseConfig).handleConnection(0xc420200000, 0x7fddbf717460, 0xc4200703c0)
        /home/marc/go/src/github.com/VolantMQ/volantmq/transport/base.go:85 +0x99
github.com/VolantMQ/volantmq/transport.(*ws).serveWs.func1(0xc420200000, 0xc4200f8280)
        /home/marc/go/src/github.com/VolantMQ/volantmq/transport/websocket.go:114 +0xf1
created by github.com/VolantMQ/volantmq/transport.(*ws).serveWs
        /home/marc/go/src/github.com/VolantMQ/volantmq/transport/websocket.go:109 +0x293
```

The client code I'm using (ws):
```
opts := pahoMQTT.NewClientOptions()
opts.AddBroker("ws://127.0.0.1:8080/")
opts.SetClientID("client-test")
opts.SetKeepAlive(time.Duration(120 * time.Second))
opts.SetConnectTimeout(time.Duration(5 * time.Second))
opts.SetAutoReconnect(false)

mqttClient := pahoMQTT.NewClient(opts)
token := mqttClient.Connect()
if token.WaitTimeout(time.Duration(5000*time.Millisecond)) || token.Error() != nil {
	log.Panic("Unable to connect to MQTT. ", token.Error())
}
```

Many thanks

**Comment by troian** [comment]
Hi, thanks for description, I take closer look

**Comment by liaoliaopro** [comment]
It is urgent... have to rollback my app to use  v0.0.3
